// Code generated by mockery v2.10.0. DO NOT EDIT.

package mocks

import (
	http "net/http"

	mock "github.com/stretchr/testify/mock"
)

// controller is an autogenerated mock type for the controller type
type Controller struct {
	mock.Mock
}

// GetAllPokemons provides a mock function with given fields: w, r
func (_m *Controller) GetAllPokemons(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// GetPokemonById provides a mock function with given fields: w, r
func (_m *Controller) GetPokemonById(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// LoadPokemonToCSV provides a mock function with given fields: w, r
func (_m *Controller) LoadPokemonToCSV(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}
